### PR TITLE
Cleanup team -> workspace

### PR DESCRIPTION
**Pull request by cdupuis**
Reworked team -> workspace. 

Re-used some resolution code from `automation-client-ts` to resolve workspaceIds from env variables.

Used `DefaultWorkspaceId` consistently across `sdm-local`.

### CODE REVIEW

**Comment by cdupuis** [comment]
@ddgenome feel free to discard in favour of your changes.

**Comment by ddgenome** [comment]
Also, I had a try/catch around the call to `getUserConfig()` since it can throw an error if the file is not readable or valid JSON.

**Comment by ddgenome** [comment]
Basically, it looked like this: https://github.com/atomist/cli/blob/bab0f89fdbfc66c8e1bf66780d7759339cd7ea53/lib/cliConfig.ts#L35-L42

**Comment by lievendoclo** [comment]
Tested with CLI, everything looks fine

**Pull request merged**
